version: '3.8'
services:
  backend:
    image: node:16
    container_name: events-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - SERVER_PORT=4000
      - DATABASE_HOST=database
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=event_management_db
      - DATABASE_PORT=5432
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: ["yarn", "dev"]

  database:
    image: postgres:16
    container_name: events-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_management_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: